# Generated by Django 4.2.5 on 2023-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
