# Generated by Django 4.2.5 on 2023-09-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_difficulty_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='difficulty',
            old_name='points',
            new_name='point',
        ),
    ]
