name: Test-server
on:
  pull_request:
    branches: 
      - main
    paths:
      - "server/app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run postgres
      run: docker compose up -d db
    - name: Run Tests
      run: |
        coverage run manage.py test --settings=config.settings.development
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
